name: CI [did-resolver]

on:
  push:
    paths:
      - "did_resolver/**"
      - ".github/**"

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    strategy:
      matrix:
        python-version: ["3.9","3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pdm
          pdm install -d
      - name: mypy
        run: |
          pdm run mypy did_resolver/
      - name: black
        run: |
          pdm run black --check --verbose did_resolver/
      - name: flake8
        uses: py-actions/flake8@v2
      - name: Test with pytest
        run: |
          pdm run -s pytest tests
